# Generated by Django 4.0.6 on 2022-08-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id_bill', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id_genre', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id_movie', models.IntegerField(primary_key=True, serialize=False)),
                ('name_movie', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=5)),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.genre')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id_room', models.IntegerField(primary_key=True, serialize=False)),
                ('name_room', models.CharField(max_length=25)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id_time', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.movie')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('idResevation', models.IntegerField(primary_key=True, serialize=False)),
                ('language_movie', models.CharField(max_length=25)),
                ('duration', models.CharField(max_length=25)),
                ('seating', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.movie')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.room')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='invoiceDetail',
            fields=[
                ('id_invoiceDetail', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.bill')),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
    ]
